In [10]:

# Easy
puzzle= ([9, 2, 0, 0, 0, 0, 5, 8, 4],
[0, 0, 0, 5, 0, 0, 0, 0, 3],
[0, 8, 3, 0, 9, 2, 0, 0, 0],
[2, 6, 0, 8, 5, 4, 0, 0, 1],
[0, 0, 5, 3, 6, 1, 0, 9, 0],
[1, 0, 0, 0, 0, 9, 0, 0, 0],
[8, 5, 0, 2, 0, 3, 0, 1, 0],
[4, 1, 2, 9, 8, 0, 0, 3, 0],
[3, 9, 0, 0, 0, 6, 8, 0, 0])

#hard
puzzle= ([0,0,3,0,0,5,0,0,4],
[5,0,0,9,8,1,0,0,0],
[0,0,0,0,0,0,0,2,0],
[2,0,0,7,0,0,9,0,0],
[0,8,0,0,9,0,0,3,0],
[0,0,9,0,0,2,0,0,1],
[0,3,0,0,0,0,0,0,0],
[0,0,0,1,4,9,0,0,5],
[9,0,0,3,0,0,8,0,0])

import numpy as np
print(np.matrix(puzzle))
depth=1
import sys
print(sys.setrecursionlimit(5000))



[[0 0 3 0 0 5 0 0 4]
 [5 0 0 9 8 1 0 0 0]
 [0 0 0 0 0 0 0 2 0]
 [2 0 0 7 0 0 9 0 0]
 [0 8 0 0 9 0 0 3 0]
 [0 0 9 0 0 2 0 0 1]
 [0 3 0 0 0 0 0 0 0]
 [0 0 0 1 4 9 0 0 5]
 [9 0 0 3 0 0 8 0 0]]
None


In [6]:
def printPuzzleValues():
    global puzzle
    print(np.matrix(puzzle))



In [7]:
def isPossible(y,x,val):
    """ Find if a matching number already exists
    in the same row or column
    """
    global puzzle
    
    for i in range(0,9):
        if puzzle[y][i] == val:
            return False
    for i in range(0,9):
        if puzzle[i][x] == val:
            return False
    x0=(x//3)*3
    y0=(y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if puzzle[y0+i][x0+j] == val:      
                return False
    #print("Is possible " ,x ,y ,val)
    return True

In [8]:
def solve():
    global puzzle
    for j in range(0,9):
        for i in range(0,9):
            if puzzle[j][i] == 0:
                for val in range(1,10):
                    if isPossible(j,i,val):
                        puzzle[j][i] = val
                        solve()
                        puzzle[j][i] = 0
                return
    print(np.matrix(puzzle))
    input("More?")
                    

In [11]:
solve()

[[8 6 3 2 7 5 1 9 4]
 [5 4 2 9 8 1 6 7 3]
 [1 9 7 4 3 6 5 2 8]
 [2 5 4 7 1 3 9 8 6]
 [6 8 1 5 9 4 2 3 7]
 [3 7 9 8 6 2 4 5 1]
 [4 3 5 6 2 8 7 1 9]
 [7 2 8 1 4 9 3 6 5]
 [9 1 6 3 5 7 8 4 2]]
More?n


In [12]:
printPuzzleValues()

[[0 0 3 0 0 5 0 0 4]
 [5 0 0 9 8 1 0 0 0]
 [0 0 0 0 0 0 0 2 0]
 [2 0 0 7 0 0 9 0 0]
 [0 8 0 0 9 0 0 3 0]
 [0 0 9 0 0 2 0 0 1]
 [0 3 0 0 0 0 0 0 0]
 [0 0 0 1 4 9 0 0 5]
 [9 0 0 3 0 0 8 0 0]]
